# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateTimeField(verbose_name='End datetime'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start datetime'),
        ),
    ]
